accept_from:  # Your telegram user ids
  - 123456789
  - 987654321
  - 1357924680
post_to: "@username"  # Target channel ID or @username
throttle: no  # Whether to throttle user messages
token: "42:TOKEN"  # Telegram bot token
