[tool.mypy]
# Config file
warn_unused_configs = true

# Import discovery
namespace_packages = true

# Platform configuration
python_version = "3.11"

# Disallow dynamic typing
disallow_any_generics = true
disallow_subclassing_any = true

# Untyped definitions and calls
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true

# None and Optional handling
no_implicit_optional = true

# Configuring warnings
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true

# Miscellaneous strictness flags
local_partial_types = true
no_implicit_reexport = true
strict_equality = true
strict = true

# Configuring error messages
show_error_context = true
show_column_numbers = true
show_error_codes = true
pretty = true

# Advanced options
plugins = [
    "pydantic.mypy",
]
warn_incomplete_stub = true

[tool.pydantic-mypy]
init_forbid_extra = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
line_length = 100
py_version = "311"
profile = "black"
known_first_party = ["randmuzposter"]
