name: Lint code

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/lint.yaml"
      - "randmuzposter/**"
      - "dev-requirements.txt"
      - "pyproject.toml"
      - "requirements.txt"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/lint.yaml"
      - "randmuzposter/**"
      - "dev-requirements.txt"
      - "pyproject.toml"
      - "requirements.txt"

permissions:
  contents: read

jobs:
  check:
    name: Check code style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip

      - name: Install packages
        run: pip install -r dev-requirements.txt -r requirements.txt

      - name: Check code style
        env:
          SRCDIR: randmuzposter
        run: |
          isort --check --diff "$SRCDIR"
          black --check --diff "$SRCDIR"
          mypy "$SRCDIR"
